spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_db
    username: root
    password: NGKm#P9lNMgV%N
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    user:
      name: admin
      password: admin123

jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  open-in-view: false
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect

springdoc:
  api-docs:
    path: /v1/api-docs       # ruta donde se genera el JSON de OpenAPI
  swagger-ui:
    path: /api-docs.html     # ruta donde se accede al Swagger UI
    display-request-duration: true  # muestra cuánto tarda cada request
    operations-sorter: method        # ordena los endpoints por metodo (GET, POST...)
  override-with-generic-response: false

management:
  endpoint:
    health:
      show-details: always

